version: '3.8'

services:
  backend:
    build: ./backend
    container_name: evently_api
    ports:
      - "5114:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/evently
      - JWT_SECRET=eventlysecret
      - NODE_ENV=development
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: evently_ui
    ports:
      - "3114:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    container_name: evently_db
    ports:
      - "27114:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
